[package]
name = "erc721_cairo"
version = "0.1.0"

[dependencies]
starknet = ">=2.4.3"

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[tool.fmt]
sort-module-level-items = true